// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVq1yeyOeY-HTrbvMjY3HKpdYaYiepuE',
    appId: '1:9141305331:web:db8babb45a3779b0849c86',
    messagingSenderId: '9141305331',
    projectId: 'to-do-39e5f',
    authDomain: 'to-do-39e5f.firebaseapp.com',
    databaseURL: 'https://to-do-39e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-39e5f.appspot.com',
    measurementId: 'G-B7ZVTJ8W61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-duZsxJYh6_kYF6NOZI2qo8-kwUaUmo',
    appId: '1:9141305331:android:b33c473383d02c4f849c86',
    messagingSenderId: '9141305331',
    projectId: 'to-do-39e5f',
    databaseURL: 'https://to-do-39e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-39e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQQvL438SJkSTizUI1hItef0_z9IYfvY',
    appId: '1:9141305331:ios:c9a9a40da4b4a893849c86',
    messagingSenderId: '9141305331',
    projectId: 'to-do-39e5f',
    databaseURL: 'https://to-do-39e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-39e5f.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQQvL438SJkSTizUI1hItef0_z9IYfvY',
    appId: '1:9141305331:ios:4a654facd0c53e74849c86',
    messagingSenderId: '9141305331',
    projectId: 'to-do-39e5f',
    databaseURL: 'https://to-do-39e5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-39e5f.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
